language: go
go:
- 1.5
before_install:
- go get golang.org/x/tools/cmd/vet golang.org/x/tools/cmd/goimports
- go get github.com/mitchellh/gox
install:
- go get github.com/bmizerany/assert
- go get github.com/ddollar/dist
- go get github.com/devangel/config
- go get github.com/ViViDboarder/gotifier
- go get github.com/bgentry/speakeasy
- go get bitbucket.org/pkg/inflect
- go get github.com/onsi/ginkgo
- go get github.com/onsi/gomega
script:
- git config --global user.email "you@example.com"
- git config --global user.name "Your Name"
- test -z "$(go fmt)"
- go vet
- go test -v
- go test -v -race
- export OS_TARGETS="darwin windows linux"
- export ARCH_TARGETS="386 amd64"
- export GO_LINKER_VALUE=$(git describe --tags --always)
- export GO_LINKER_SYMBOL="main.Version"
- gox -os "$OS_TARGETS" -arch="$ARCH_TARGETS" -ldflags "-X $GO_LINKER_SYMBOL $GO_LINKER_VALUE"
- mkdir -p darwin/amd64 && cp force_darwin_amd64 darwin/amd64/force
- mkdir -p darwin/386 && cp force_darwin_386 darwin/386/force
- mkdir -p windows/amd64 && cp force_windows_amd64.exe windows/amd64/force.exe
- mkdir -p windows/386 && cp force_windows_386.exe windows/386/force.exe
- mkdir -p linux/amd64 && cp force_linux_amd64 linux/amd64/force
- mkdir -p linux/386 && cp force_linux_386 linux/386/force
deploy:
- provider: releases
  skip_cleanup: true
  api_key:
    secure: fkmUJ0tn/Z8q7ytQVJLXEKGQ599Wx0gCCuRdxLk7m0B4Z4S6vaNjStMafizp4Fbg0scyBVqFPkzaI8pm5U5C5owJySFE+zbtHx9nAyZTyK+BJmLdHoLHGVy9NHNAw5NgKgvr4nsIbz8gQ5eEuFBnj0azwg4kLcZILM8bHIvFq4M=
  file:
    - force_darwin_amd64
    - force_darwin_386
    - force_linux_amd64
    - force_linux_386
    - force_windows_amd64.exe
    - force_windows_386.exe
  on:
    tags: true
    repo: cwarden/force
