package metadata

func init() {
	Registry.Register("Package", NewPackage)

	// CustomObject sub-types
	Registry.Register("BusinessProcess", NewBusinessProcess)
	Registry.Register("CustomField", NewCustomField)
	Registry.Register("CompactLayout", NewCompactLayout)
	Registry.Register("FieldSet", NewFieldSet)
	Registry.Register("ListView", NewListView)
	Registry.Register("RecordType", NewRecordType)
	Registry.Register("SharingReason", NewSharingReason)
	Registry.Register("ValidationRule", NewValidationRule)
	Registry.Register("WebLink", NewWebLink)

	// CustomObjectTranslation and it's child CustomFieldTranslation
	Registry.Register("CustomObjectTranslation", NewCustomObjectTranslationComponent)
	Registry.Register("CustomFieldTranslation", NewCustomObjectTranslationComponent)

	// Types with separate content and metadata
	Registry.RegisterContentType("ApexClass", "classes")
	Registry.RegisterContentType("ApexTrigger", "triggers")
	Registry.RegisterContentType("ApexPage", "pages")
	Registry.RegisterContentType("ApexComponent", "components")
	Registry.RegisterContentType("WaveDataflow", "wave")
	Registry.RegisterContentType("WaveRecipe", "wave")
	Registry.RegisterContentType("StaticResource", "staticresources")

	// Types stored within folders
	Registry.RegisterFolderedType("Dashboard", "dashboards")
	Registry.RegisterFolderedType("Document", "documents")
	Registry.RegisterFolderedType("Report", "reports")
	// EmailTemplates are foldered and have separate -meta.xml files.
	Registry.Register("EmailTemplate", NewEmailTemplate)
	// The folders for foldered types
	Registry.RegisterFolderType("DashboardFolder", "Dashboard", "dashboards")
	Registry.RegisterFolderType("DocumentFolder", "Document", "documents")
	Registry.RegisterFolderType("EmailFolder", "EmailTemplate", "email")
	Registry.RegisterFolderType("ReportFolder", "Report", "reports")

	// Types made of multiple files within a folder with a single metadata file
	Registry.RegisterBundledType("AuraDefinitionBundle", "aura")
	Registry.RegisterBundledType("LightningComponentBundle", "lwc")

	// Experience Bundles have a directory and a metadata type at the same level
	Registry.Register("ExperienceBundle", NewExperienceBundle)

	// Normal single-file types
	Registry.RegisterBaseType("ActionLinkGroupTemplate", "actionLinkGroupTemplates")
	Registry.RegisterBaseType("AnalyticSnapshot", "analyticSnapshots")
	Registry.RegisterBaseType("ApexEmailNotifications", "apexEmailNotifications")
	Registry.RegisterBaseType("AppMenu", "appMenus")
	Registry.RegisterBaseType("ApprovalProcess", "approvalProcesses")
	Registry.RegisterBaseType("AssignmentRules", "assignmentRules")
	Registry.RegisterBaseType("Audience", "audience")
	Registry.RegisterBaseType("AuthProvider", "authproviders")
	Registry.RegisterBaseType("AutoResponseRules", "autoResponseRules")
	Registry.RegisterBaseType("CallCenter", "callCenters")
	Registry.RegisterBaseType("Certificate", "certs")
	Registry.RegisterBaseType("ChannelLayout", "channelLayouts")
	Registry.RegisterBaseType("CleanDataService", "cleanDataServices")
	Registry.RegisterBaseType("Community", "communities")
	Registry.RegisterBaseType("ConnectedApp", "connectedApps")
	Registry.RegisterBaseType("ContentAsset", "contentassets")
	Registry.RegisterBaseType("CorsWhitelistOrigin", "corsWhitelistOrigins")
	Registry.RegisterBaseType("CspTrustedSite", "cspTrustedSites")
	Registry.RegisterBaseType("CustomApplication", "applications")
	Registry.RegisterBaseType("CustomApplicationComponent", "customApplicationComponents")
	Registry.RegisterBaseType("CustomFeedFilter", "feedFilters")
	Registry.RegisterBaseType("CustomHelpMenuSection", "customHelpMenuSections")
	Registry.RegisterBaseType("CustomLabels", "labels")
	Registry.RegisterBaseType("CustomMetadata", "customMetadata")
	Registry.RegisterBaseType("CustomNotificationType", "notificationtypes")
	Registry.RegisterBaseType("CustomObject", "objects")
	Registry.RegisterBaseType("CustomPageWebLink", "weblinks")
	Registry.RegisterBaseType("CustomPermission", "customPermissions")
	Registry.RegisterBaseType("CustomSite", "sites")
	Registry.RegisterBaseType("CustomTab", "tabs")
	Registry.RegisterBaseType("DataCategoryGroup", "datacategorygroups")
	Registry.RegisterBaseType("DataWeaveResource", "dw")
	Registry.RegisterBaseType("DelegateGroup", "delegateGroups")
	Registry.RegisterBaseType("DuplicateRule", "duplicateRules")
	Registry.RegisterBaseType("EmbeddedServiceConfig", "EmbeddedServiceConfig")
	Registry.RegisterBaseType("EscalationRules", "escalationRules")
	Registry.RegisterBaseType("ExternalCredential", "externalCredentials")
	Registry.RegisterBaseType("ExternalDataSource", "dataSources")
	Registry.RegisterBaseType("FlexiPage", "flexipages")
	Registry.RegisterBaseType("FlowDefinition", "flowDefinitions")
	Registry.RegisterBaseType("Flow", "flows")
	Registry.RegisterBaseType("FlowTest", "flowtests")
	Registry.RegisterBaseType("GlobalPicklist", "globalPicklists")
	Registry.RegisterBaseType("GlobalValueSet", "globalValueSets")
	Registry.RegisterBaseType("GlobalValueSetTranslation", "globalValueSetTranslations")
	Registry.RegisterBaseType("Group", "groups")
	Registry.RegisterBaseType("HomePageComponent", "homePageComponents")
	Registry.RegisterBaseType("HomePageLayout", "homePageLayouts")
	Registry.RegisterBaseType("InstalledPackage", "installedPackages")
	Registry.RegisterBaseType("Layout", "layouts")
	Registry.RegisterBaseType("LeadConvertSettings", "LeadConvertSettings")
	Registry.RegisterBaseType("Letterhead", "letterhead")
	Registry.RegisterBaseType("LightningMessageChannel", "messageChannels")
	Registry.RegisterBaseType("MatchingRule", "matchingRules")
	Registry.RegisterBaseType("MatchingRules", "matchingRules")
	Registry.RegisterBaseType("NamedCredential", "namedCredentials")
	Registry.RegisterBaseType("Network", "networks")
	Registry.RegisterBaseType("NotificationTypeConfig", "notificationTypeConfig")
	Registry.RegisterBaseType("OmniDataTransform", "omniDataTransforms")
	Registry.RegisterBaseType("OmniIntegrationProcedure", "omniIntegrationProcedures")
	Registry.RegisterBaseType("OmniInteractionConfig", "OmniInteractionConfig")
	Registry.RegisterBaseType("OmniScript", "omniScripts")
	Registry.RegisterBaseType("OmniUiCard", "omniUiCard")
	Registry.RegisterBaseType("PathAssistant", "pathAssistants")
	Registry.RegisterBaseType("PermissionSetGroup", "permissionsetgroups")
	Registry.RegisterBaseType("PermissionSet", "permissionsets")
	Registry.RegisterBaseType("PlatformCachePartition", "cachePartitions")
	Registry.RegisterBaseType("PlatformEventChannelMember", "platformEventChannelMembers")
	Registry.RegisterBaseType("PlatformEventChannel", "platformEventChannels")
	Registry.RegisterBaseType("PlatformEventSubscriberConfig", "PlatformEventSubscriberConfigs")
	Registry.RegisterBaseType("PostTemplate", "postTemplates")
	Registry.RegisterBaseType("Profile", "profiles")
	Registry.RegisterBaseType("ProfileSessionSetting", "profileSessionSettings")
	Registry.RegisterBaseType("Queue", "queues")
	Registry.RegisterBaseType("QuickAction", "quickActions")
	Registry.RegisterBaseType("RemoteSiteSetting", "remoteSiteSettings")
	Registry.RegisterBaseType("ReportType", "reportTypes")
	Registry.RegisterBaseType("RestrictionRule", "restrictionRules")
	Registry.RegisterBaseType("Role", "roles")
	Registry.RegisterBaseType("Scontrol", "scontrols")
	Registry.RegisterBaseType("SharingRules", "sharingRules")
	Registry.RegisterBaseType("SiteDotCom", "siteDotComSites")
	Registry.RegisterBaseType("StandardValueSet", "standardValueSets")
	Registry.RegisterBaseType("SynonymDictionary", "synonymDictionaries")
	Registry.RegisterBaseType("Translations", "translations")
	Registry.RegisterBaseType("WaveApplication", "wave")
	Registry.RegisterBaseType("WaveDataset", "wave")
	Registry.RegisterBaseType("Workflow", "workflows")

	// Settings are deployed as type Settings
	Registry.RegisterSettingsType("Settings", "settings")
	Registry.RegisterSettingsType("AccountIntelligenceSettings", "settings")
	Registry.RegisterSettingsType("AccountSettings", "settings")
	Registry.RegisterSettingsType("ActionsSettings", "settings")
	Registry.RegisterSettingsType("ActivitiesSettings", "settings")
	Registry.RegisterSettingsType("AddressSettings", "settings")
	Registry.RegisterSettingsType("Ai4mSettings", "settings")
	Registry.RegisterSettingsType("AnalyticsSettings", "settings")
	Registry.RegisterSettingsType("ApexSettings", "settings")
	Registry.RegisterSettingsType("AppAnalyticsSettings", "settings")
	Registry.RegisterSettingsType("AppExperienceSettings", "settings")
	Registry.RegisterSettingsType("AutomatedContactsSettings", "settings")
	Registry.RegisterSettingsType("BlockchainSettings", "settings")
	Registry.RegisterSettingsType("BotSettings", "settings")
	Registry.RegisterSettingsType("BusinessHoursSettings", "settings")
	Registry.RegisterSettingsType("CampaignSettings", "settings")
	Registry.RegisterSettingsType("CaseSettings", "settings")
	Registry.RegisterSettingsType("ChatterAnswersSettings", "settings")
	Registry.RegisterSettingsType("ChatterEmailsMDSettings", "settings")
	Registry.RegisterSettingsType("ChatterSettings", "settings")
	Registry.RegisterSettingsType("CodeBuilderSettings", "settings")
	Registry.RegisterSettingsType("CommerceSettings", "settings")
	Registry.RegisterSettingsType("CommunitiesSettings", "settings")
	Registry.RegisterSettingsType("CompanySettings", "settings")
	Registry.RegisterSettingsType("ConnectedAppSettings", "settings")
	Registry.RegisterSettingsType("ContentSettings", "settings")
	Registry.RegisterSettingsType("ContractSettings", "settings")
	Registry.RegisterSettingsType("ConversationalIntelligenceSettings", "settings")
	Registry.RegisterSettingsType("CurrencySettings", "settings")
	Registry.RegisterSettingsType("CustomAddressFieldSettings", "settings")
	Registry.RegisterSettingsType("CustomerDataPlatformSettings", "settings")
	Registry.RegisterSettingsType("CustomizablePropensityScoringSettings", "settings")
	Registry.RegisterSettingsType("DeploymentSettings", "settings")
	Registry.RegisterSettingsType("DevHubSettings", "settings")
	Registry.RegisterSettingsType("DiscoverySettings", "settings")
	Registry.RegisterSettingsType("DocumentChecklistSettings", "settings")
	Registry.RegisterSettingsType("DynamicFormsSettings", "settings")
	Registry.RegisterSettingsType("EACSettings", "settings")
	Registry.RegisterSettingsType("EinsteinAgentSettings", "settings")
	Registry.RegisterSettingsType("EinsteinDocumentCaptureSettings", "settings")
	Registry.RegisterSettingsType("EmailAdministrationSettings", "settings")
	Registry.RegisterSettingsType("EmailIntegrationSettings", "settings")
	Registry.RegisterSettingsType("EmailTemplateSettings", "settings")
	Registry.RegisterSettingsType("EmployeeFieldAccessSettings", "settings")
	Registry.RegisterSettingsType("EmployeeUserSettings", "settings")
	Registry.RegisterSettingsType("EncryptionKeySettings", "settings")
	Registry.RegisterSettingsType("EnhancedNotesSettings", "settings")
	Registry.RegisterSettingsType("EntitlementSettings", "settings")
	Registry.RegisterSettingsType("EssentialsSettings", "settings")
	Registry.RegisterSettingsType("EventSettings", "settings")
	Registry.RegisterSettingsType("ExperienceBundleSettings", "settings")
	Registry.RegisterSettingsType("ExternalClientAppSettings", "settings")
	Registry.RegisterSettingsType("FilesConnectSettings", "settings")
	Registry.RegisterSettingsType("FileUploadAndDownloadSecuritySettings", "settings")
	Registry.RegisterSettingsType("FlowSettings", "settings")
	Registry.RegisterSettingsType("ForecastingSettings", "settings")
	Registry.RegisterSettingsType("FormulaSettings", "settings")
	Registry.RegisterSettingsType("GoogleAppsSettings", "settings")
	Registry.RegisterSettingsType("HighVelocitySalesSettings", "settings")
	Registry.RegisterSettingsType("IdeasSettings", "settings")
	Registry.RegisterSettingsType("IdentityProviderSettings", "settings")
	Registry.RegisterSettingsType("IncidentMgmtSettings", "settings")
	Registry.RegisterSettingsType("IndustriesEinsteinFeatureSettings", "settings")
	Registry.RegisterSettingsType("IndustriesManufacturingSettings", "settings")
	Registry.RegisterSettingsType("IndustriesSettings", "settings")
	Registry.RegisterSettingsType("InvocableActionSettings", "settings")
	Registry.RegisterSettingsType("KnowledgeGenerationSettings", "settings")
	Registry.RegisterSettingsType("KnowledgeSettings", "settings")
	Registry.RegisterSettingsType("LanguageSettings", "settings")
	Registry.RegisterSettingsType("LeadConfigSettings", "settings")
	Registry.RegisterSettingsType("LightningExperienceSettings", "settings")
	Registry.RegisterSettingsType("LiveAgentSettings", "settings")
	Registry.RegisterSettingsType("MacroSettings", "settings")
	Registry.RegisterSettingsType("MailMergeSettings", "settings")
	Registry.RegisterSettingsType("MapsAndLocationSettings", "settings")
	Registry.RegisterSettingsType("MeetingsSettings", "settings")
	Registry.RegisterSettingsType("MobileSettings", "settings")
	Registry.RegisterSettingsType("MyDomainSettings", "settings")
	Registry.RegisterSettingsType("NameSettings", "settings")
	Registry.RegisterSettingsType("NotificationsSettings", "settings")
	Registry.RegisterSettingsType("OauthOidcSettings", "settings")
	Registry.RegisterSettingsType("ObjectLinkingSettings", "settings")
	Registry.RegisterSettingsType("OmniChannelPricingSettings", "settings")
	Registry.RegisterSettingsType("OmniChannelSettings", "settings")
	Registry.RegisterSettingsType("OnlineSalesSettings", "settings")
	Registry.RegisterSettingsType("OpportunityScoreSettings", "settings")
	Registry.RegisterSettingsType("OpportunitySettings", "settings")
	Registry.RegisterSettingsType("OrderSettings", "settings")
	Registry.RegisterSettingsType("OrgSettings", "settings")
	Registry.RegisterSettingsType("PardotEinsteinSettings", "settings")
	Registry.RegisterSettingsType("PardotSettings", "settings")
	Registry.RegisterSettingsType("PartyDataModelSettings", "settings")
	Registry.RegisterSettingsType("PathAssistantSettings", "settings")
	Registry.RegisterSettingsType("PaymentsManagementEnabledSettings", "settings")
	Registry.RegisterSettingsType("PicklistSettings", "settings")
	Registry.RegisterSettingsType("PlatformEncryptionSettings", "settings")
	Registry.RegisterSettingsType("PlatformEventSettings", "settings")
	Registry.RegisterSettingsType("PortalsSettings", "settings")
	Registry.RegisterSettingsType("PredictionBuilderSettings", "settings")
	Registry.RegisterSettingsType("PrivacySettings", "settings")
	Registry.RegisterSettingsType("ProductSettings", "settings")
	Registry.RegisterSettingsType("QuickTextSettings", "settings")
	Registry.RegisterSettingsType("QuoteSettings", "settings")
	Registry.RegisterSettingsType("RealTimeEventSettings", "settings")
	Registry.RegisterSettingsType("RecommendationBuilderSettings", "settings")
	Registry.RegisterSettingsType("RecordPageSettings", "settings")
	Registry.RegisterSettingsType("RetailExecutionSettings", "settings")
	Registry.RegisterSettingsType("SandboxSettings", "settings")
	Registry.RegisterSettingsType("SceGlobalModelOptOutSettings", "settings")
	Registry.RegisterSettingsType("SchemaSettings", "settings")
	Registry.RegisterSettingsType("SearchSettings", "settings")
	Registry.RegisterSettingsType("SecuritySettings", "settings")
	Registry.RegisterSettingsType("ServiceCloudVoiceSettings", "settings")
	Registry.RegisterSettingsType("ServiceSetupAssistantSettings", "settings")
	Registry.RegisterSettingsType("SharingSettings", "settings")
	Registry.RegisterSettingsType("SiteSettings", "settings")
	Registry.RegisterSettingsType("SocialCustomerServiceSettings", "settings")
	Registry.RegisterSettingsType("SourceTrackingSettings", "settings")
	Registry.RegisterSettingsType("SurveySettings", "settings")
	Registry.RegisterSettingsType("SystemNotificationSettings", "settings")
	Registry.RegisterSettingsType("Territory2Settings", "settings")
	Registry.RegisterSettingsType("TrailheadSettings", "settings")
	Registry.RegisterSettingsType("TrialOrgSettings", "settings")
	Registry.RegisterSettingsType("UserEngagementSettings", "settings")
	Registry.RegisterSettingsType("UserInterfaceSettings", "settings")
	Registry.RegisterSettingsType("UserManagementSettings", "settings")
	Registry.RegisterSettingsType("VoiceSettings", "settings")
	Registry.RegisterSettingsType("WebToXSettings", "settings")
	Registry.RegisterSettingsType("WorkDotComSettings", "settings")

	// TODO:
	// Unzipped Static Resources
}
