package metadata

func init() {
	Registry.Register("Package", NewPackage)

	// CustomObject sub-types
	Registry.Register("BusinessProcess", NewBusinessProcess)
	Registry.Register("CustomField", NewCustomField)
	Registry.Register("CompactLayout", NewCompactLayout)
	Registry.Register("FieldSet", NewFieldSet)
	Registry.Register("ListView", NewListView)
	Registry.Register("RecordType", NewRecordType)
	Registry.Register("SharingReason", NewSharingReason)
	Registry.Register("ValidationRule", NewValidationRule)
	Registry.Register("WebLink", NewWebLink)

	// CustomObjectTranslation and it's child CustomFieldTranslation
	Registry.Register("CustomObjectTranslation", NewCustomObjectTranslationComponent)
	Registry.Register("CustomFieldTranslation", NewCustomObjectTranslationComponent)

	// Types with separate content and metadata
	Registry.RegisterContentType("ApexClass", "classes")
	Registry.RegisterContentType("ApexTrigger", "triggers")
	Registry.RegisterContentType("ApexPage", "pages")
	Registry.RegisterContentType("ApexComponent", "components")
	Registry.RegisterContentType("WaveDataflow", "wave")
	Registry.RegisterContentType("WaveRecipe", "wave")
	Registry.RegisterContentType("StaticResource", "staticresources")

	// Types stored within folders
	Registry.RegisterFolderedType("Dashboard", "dashboards")
	Registry.RegisterFolderedType("Document", "documents")
	Registry.RegisterFolderedType("Report", "reports")
	// EmailTemplates are foldered and have separate -meta.xml files.
	Registry.Register("EmailTemplate", NewEmailTemplate)
	// The folders for foldered types
	Registry.RegisterFolderType("DashboardFolder", "Dashboard", "dashboards")
	Registry.RegisterFolderType("DocumentFolder", "Document", "documents")
	Registry.RegisterFolderType("EmailFolder", "EmailTemplate", "email")
	Registry.RegisterFolderType("ReportFolder", "Report", "reports")

	// Types made of multiple files within a folder with a single metadata file
	Registry.RegisterBundledType("AuraDefinitionBundle", "aura")
	Registry.RegisterBundledType("LightningComponentBundle", "lwc")

	// Experience Bundles have a directory and a metadata type at the same level
	Registry.Register("ExperienceBundle", NewExperienceBundle)

	// Normal single-file types
	Registry.RegisterBaseType("ActionLinkGroupTemplate", "actionLinkGroupTemplates")
	Registry.RegisterBaseType("AnalyticSnapshot", "analyticSnapshots")
	Registry.RegisterBaseType("ApexEmailNotifications", "apexEmailNotifications")
	Registry.RegisterBaseType("AppMenu", "appMenus")
	Registry.RegisterBaseType("ApprovalProcess", "approvalProcesses")
	Registry.RegisterBaseType("AssignmentRules", "assignmentRules")
	Registry.RegisterBaseType("Audience", "audience")
	Registry.RegisterBaseType("AuthProvider", "authproviders")
	Registry.RegisterBaseType("AutoResponseRules", "autoResponseRules")
	Registry.RegisterBaseType("CallCenter", "callCenters")
	Registry.RegisterBaseType("Certificate", "certs")
	Registry.RegisterBaseType("ChannelLayout", "channelLayouts")
	Registry.RegisterBaseType("CleanDataService", "cleanDataServices")
	Registry.RegisterBaseType("Community", "communities")
	Registry.RegisterBaseType("ConnectedApp", "connectedApps")
	Registry.RegisterBaseType("ContentAsset", "contentassets")
	Registry.RegisterBaseType("CorsWhitelistOrigin", "corsWhitelistOrigins")
	Registry.RegisterBaseType("CspTrustedSite", "cspTrustedSites")
	Registry.RegisterBaseType("CustomApplication", "applications")
	Registry.RegisterBaseType("CustomApplicationComponent", "customApplicationComponents")
	Registry.RegisterBaseType("CustomFeedFilter", "feedFilters")
	Registry.RegisterBaseType("CustomHelpMenuSection", "customHelpMenuSections")
	Registry.RegisterBaseType("CustomLabels", "labels")
	Registry.RegisterBaseType("CustomMetadata", "customMetadata")
	Registry.RegisterBaseType("CustomNotificationType", "notificationtypes")
	Registry.RegisterBaseType("CustomObject", "objects")
	Registry.RegisterBaseType("CustomPageWebLink", "weblinks")
	Registry.RegisterBaseType("CustomPermission", "customPermissions")
	Registry.RegisterBaseType("CustomSite", "sites")
	Registry.RegisterBaseType("CustomTab", "tabs")
	Registry.RegisterBaseType("DataCategoryGroup", "datacategorygroups")
	Registry.RegisterBaseType("DataWeaveResource", "dw")
	Registry.RegisterBaseType("DelegateGroup", "delegateGroups")
	Registry.RegisterBaseType("DuplicateRule", "duplicateRules")
	Registry.RegisterBaseType("EmbeddedServiceConfig", "EmbeddedServiceConfig")
	Registry.RegisterBaseType("EscalationRules", "escalationRules")
	Registry.RegisterBaseType("ExternalCredential", "externalCredentials")
	Registry.RegisterBaseType("ExternalDataSource", "dataSources")
	Registry.RegisterBaseType("FlexiPage", "flexipages")
	Registry.RegisterBaseType("FlowDefinition", "flowDefinitions")
	Registry.RegisterBaseType("Flow", "flows")
	Registry.RegisterBaseType("FlowTest", "flowtests")
	Registry.RegisterBaseType("GlobalPicklist", "globalPicklists")
	Registry.RegisterBaseType("GlobalValueSet", "globalValueSets")
	Registry.RegisterBaseType("GlobalValueSetTranslation", "globalValueSetTranslations")
	Registry.RegisterBaseType("Group", "groups")
	Registry.RegisterBaseType("HomePageComponent", "homePageComponents")
	Registry.RegisterBaseType("HomePageLayout", "homePageLayouts")
	Registry.RegisterBaseType("InstalledPackage", "installedPackages")
	Registry.RegisterBaseType("Layout", "layouts")
	Registry.RegisterBaseType("LeadConvertSettings", "LeadConvertSettings")
	Registry.RegisterBaseType("Letterhead", "letterhead")
	Registry.RegisterBaseType("LightningMessageChannel", "messageChannels")
	Registry.RegisterBaseType("MatchingRule", "matchingRules")
	Registry.RegisterBaseType("MatchingRules", "matchingRules")
	Registry.RegisterBaseType("NamedCredential", "namedCredentials")
	Registry.RegisterBaseType("Network", "networks")
	Registry.RegisterBaseType("NotificationTypeConfig", "notificationTypeConfig")
	Registry.RegisterBaseType("OmniDataTransform", "omniDataTransforms")
	Registry.RegisterBaseType("OmniIntegrationProcedure", "omniIntegrationProcedures")
	Registry.RegisterBaseType("OmniScript", "omniScripts")
	Registry.RegisterBaseType("OmniUiCard", "omniUiCard")
	Registry.RegisterBaseType("PathAssistant", "pathAssistants")
	Registry.RegisterBaseType("PermissionSetGroup", "permissionsetgroups")
	Registry.RegisterBaseType("PermissionSet", "permissionsets")
	Registry.RegisterBaseType("PlatformCachePartition", "cachePartitions")
	Registry.RegisterBaseType("PlatformEventChannelMember", "platformEventChannelMembers")
	Registry.RegisterBaseType("PlatformEventChannel", "platformEventChannels")
	Registry.RegisterBaseType("PlatformEventSubscriberConfig", "PlatformEventSubscriberConfigs")
	Registry.RegisterBaseType("PostTemplate", "postTemplates")
	Registry.RegisterBaseType("Profile", "profiles")
	Registry.RegisterBaseType("ProfileSessionSetting", "profileSessionSettings")
	Registry.RegisterBaseType("Queue", "queues")
	Registry.RegisterBaseType("QuickAction", "quickActions")
	Registry.RegisterBaseType("RemoteSiteSetting", "remoteSiteSettings")
	Registry.RegisterBaseType("ReportType", "reportTypes")
	Registry.RegisterBaseType("RestrictionRule", "restrictionRules")
	Registry.RegisterBaseType("Role", "roles")
	Registry.RegisterBaseType("Scontrol", "scontrols")
	Registry.RegisterBaseType("Settings", "settings")
	Registry.RegisterBaseType("SharingRules", "sharingRules")
	Registry.RegisterBaseType("SiteDotCom", "siteDotComSites")
	Registry.RegisterBaseType("StandardValueSet", "standardValueSets")
	Registry.RegisterBaseType("SynonymDictionary", "synonymDictionaries")
	Registry.RegisterBaseType("Translations", "translations")
	Registry.RegisterBaseType("WaveApplication", "wave")
	Registry.RegisterBaseType("WaveDataset", "wave")
	Registry.RegisterBaseType("Workflow", "workflows")

	// TODO:
	// Unzipped Static Resources
	// Settings: Each has its own top-level element
}
